apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: gatekeeper-system
  name: gatekeeper-helm
resources:
  - namespace.yaml
helmCharts:
  - releaseName: gatekeeper
    namespace: gatekeeper-system
    repo: https://open-policy-agent.github.io/gatekeeper/charts
    version: 3.16.3
    name: gatekeeper
