apiVersion: constraints.gatekeeper.sh/v1beta1
kind: PodSecurityStandardLabel
metadata:
  name: require-pss-label
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  parameters:
    preferredStandard: "baseline"
