apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NetworkPolicyDenyAll
metadata:
  name: network-policies-deny-all
spec:
  enforcementAction: warn
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
