apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: gatekeeper-constraint-tmpls
resources:
  - network-policies-deny-all.yaml
  - pod-security-standards.yaml
  - deployment-resource.yaml
